version: "3"
services:
  mysql:
    # build: ./mysql/
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testdb
